version: "3"

tasks:
  deploy:
    desc: "Build task to build and deploy full stack"
    cmds:
      - task: sam-build
      - task: sam-validate
      - task: sam-deploy
      - task: cleanup
      - echo "[INFO] Script completed successfully."

  delete:
    desc: "Delete task to clean out S3 buckets and delete full stack"
    cmds:
      - task: sam-delete
      - task: cleanup
      - echo "[INFO] Script completed successfully."

  sam-build:
    desc: "Build SAM application"
    cmds:
      - echo "[INFO] Starting SAM build."
      - sam build
    silent: false
    ignore_error: false

  sam-deploy:
    desc: "Deploy SAM application"
    cmds:
      - echo "[INFO] Starting SAM deployment."
      - sam deploy
    silent: false

  sam-validate:
    desc: "Validate SAM template"
    cmds:
      - echo "[INFO] Validating SAM template."
      - sam validate --lint
    silent: false
    ignore_error: false

  sam-delete:
    desc: "Upload Glue Job script to S3"
    cmds:
      - sam delete --no-prompts
    silent: false
    ignore_error: false

  cleanup:
    desc: "Perform cleanup"
    cmds:
      - echo "[INFO] No cleanup logic... exiting."
    silent: false
    ignore_error: false
  put-item:
    desc: Perform a DynamoDB PutItem request
    vars:
      table_name: "poc-users"
    cmds:
      - |
        echo '{
          "TableName": "{{.table_name}}",
          "Item": {
            "pk": {
              "S": "USER#auth0|66199504eddfc16953adc92e"
            },
            "sk": {
              "S": "METADATA"
            },
            "email": {
              "S": "admin@example.org"
            },
            "status": {
              "S": "ACTIVE"
            },
            "organizations": {
              "L": [
                {
                  "S": "101db94c-28c3-47c8-9fd9-e59219a89c78"
                },
                {
                  "S": "43ca7b5b-dfc5-410a-af28-543d8cde73f8"
                }
              ]
            }
          }
        }' > /tmp/dynamodb-put-item.json
      - aws dynamodb put-item --cli-input-json file:///tmp/dynamodb-put-item.json
      - rm /tmp/dynamodb-put-item.json
  delete-item:
    desc: Perform a DynamoDB DeleteItem request
    vars:
      table_name: "poc-users"
      pk: "USER#auth0|66199504eddfc16953adc92e"
      sk: "METADATA"
    cmds:
      - |
        echo '{
          "TableName": "{{.table_name}}",
          "Key": {
            "pk": {
              "S": "{{.pk}}"
            },
            "sk": {
              "S": "{{.sk}}"
            }
          }
        }' > /tmp/dynamodb-delete-item.json
      - aws dynamodb delete-item --cli-input-json file:///tmp/dynamodb-delete-item.json
      - rm /tmp/dynamodb-delete-item.json

  test:
    desc: Run tests
    cmds:
      - go test -v ./...
    sources:
      - ./**/*.go
    generates:
      - coverage.out

  test:watch:
    desc: Run tests in watch mode
    cmds:
      - go test -v ./... -count=1
    sources:
      - ./**/*.go
    generates:
      - coverage.out
    watch: true

  user:create:
    desc: Create a new user record in DynamoDB
    vars:
      user_id: '{{.USER_ID | default "auth0|123"}}'
      email: '{{.EMAIL | default "user@example.com"}}'
      orgs: '{{.ORGS | default "[]"}}'
    cmds:
      - |
        echo '{
          "TableName": "poc-users",
          "Item": {
            "pk": {
              "S": "USER#{{.user_id}}"
            },
            "sk": {
              "S": "METADATA"
            },
            "email": {
              "S": "{{.email}}"
            },
            "status": {
              "S": "ACTIVE"
            },
            "organizations": {
              "L": {{.orgs}}
            }
          }
        }' > /tmp/dynamodb-put-item.json
      - aws dynamodb put-item --cli-input-json file:///tmp/dynamodb-put-item.json
      - rm /tmp/dynamodb-put-item.json

  user:update-orgs:
    desc: Update a user's organizations
    vars:
      user_id: '{{.USER_ID}}'
      orgs: '{{.ORGS}}'
    cmds:
      - |
        echo '{
          "TableName": "poc-users",
          "Key": {
            "pk": {
              "S": "USER#{{.user_id}}"
            },
            "sk": {
              "S": "METADATA"
            }
          },
          "UpdateExpression": "SET organizations = :orgs",
          "ExpressionAttributeValues": {
            ":orgs": {
              "L": {{.orgs}}
            }
          }
        }' > /tmp/dynamodb-update-item.json
      - aws dynamodb update-item --cli-input-json file:///tmp/dynamodb-update-item.json
      - rm /tmp/dynamodb-update-item.json

  user:delete:
    desc: Delete a user record
    vars:
      user_id: '{{.USER_ID}}'
    cmds:
      - |
        echo '{
          "TableName": "poc-users",
          "Key": {
            "pk": {
              "S": "USER#{{.user_id}}"
            },
            "sk": {
              "S": "METADATA"
            }
          }
        }' > /tmp/dynamodb-delete-item.json
      - aws dynamodb delete-item --cli-input-json file:///tmp/dynamodb-delete-item.json
      - rm /tmp/dynamodb-delete-item.json
